// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of one backfill page: how many ids were enqueued, and the cursor to
 * resume from (`?after=`). `enqueued == 0` means the sweep is drained.
 */
export type BackfillResult = { enqueued: bigint, last_id: bigint, };
