// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a one-time email code was issued — decides its scope and the mail copy.
 * `Login` exchanges for a session (passwordless); `PasswordReset` authorises
 * setting a new password. Mirrors the `email_codes.purpose` CHECK.
 */
export type CodePurpose = "login" | "password_reset";
