// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Comment = { id: bigint, post_id: bigint, author_id: bigint, body: string, created_at: string, 
/**
 * DISTINCT users with an active (non-retracted) like on this comment, live
 * from the interaction journal (ADR 0012; distinct actors, not journal rows
 * — see `Post::like_count`).
 */
like_count: bigint, 
/**
 * Whether the REQUESTING viewer holds an active like on this comment.
 * `false` for anonymous reads.
 */
liked_by_me: boolean, };
