// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Comment = { id: bigint, post_id: bigint, author_id: bigint, body: string, created_at: string, };
