// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * Response for `GET /auth/me`: the current session's user id and role, so the
 * frontend can gate operator-only navigation and routes.
 */
export type CurrentUser = { user_id: bigint, role: Role, };
