// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * Response for `GET /auth/me`: the current session's user id and role (so the
 * frontend can gate operator-only navigation) plus the user's own referral
 * code (so the UI can render a share link, MASTERPLAN P-2).
 */
export type CurrentUser = { user_id: bigint, role: Role, referral_code: string, };
