// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for the email-first login step: enter the email, then the UI asks for a
 * password to sign in (if it exists) or to create an account (if it doesn't).
 */
export type EmailCheckRequest = { email: string, };
