// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether an account already exists for the email. NOTE: this deliberately reveals
 * account existence (user enumeration) to enable the email-first UX — an accepted
 * product trade-off; the endpoint must stay rate-limited (see the per-route
 * rate-limit follow-up).
 */
export type EmailCheckResult = { exists: boolean, };
