// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Post } from "./Post";

/**
 * One page of the personalized feed. `next_cursor` is `None` on the last
 * page; otherwise pass it back verbatim as `?cursor=` for the next page.
 */
export type FeedPage = { items: Array<Post>, next_cursor: string | null, };
