// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user's current off-chain gem balance.
 */
export type GemBalance = { user_id: bigint, 
/**
 * PT base units.
 */
balance: bigint, };
