// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A snapshot of how far ingestion analysis has progressed over the corpus. Pure
 * observability for an operator sizing a backfill or watching a re-analysis sweep.
 */
export type IngestionStatus = { 
/**
 * Visible posts that have a `content_signals` row.
 */
analyzed: bigint, 
/**
 * Visible posts with no signals row yet (what a full backfill would enqueue).
 */
unanalyzed: bigint, 
/**
 * Analysed-post counts keyed by the model version that produced them.
 */
by_model_version: { [key in string]: bigint }, };
