// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create request. `post_id` comes from the path and `author_id` from the session,
 * so the body carries only the text.
 */
export type NewComment = { body: string, };
