// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InteractionType } from "./InteractionType";

/**
 * Request to record an interaction. Exactly one of `target_id` (the other
 * user), `post_id`, or `comment_id` identifies what is interacted with — a
 * like targets a post or a comment, a follow targets a user, etc. The service
 * normalises the triple to ONE canonical shape (see `record`), so a client
 * sending redundant ids cannot mint distinct dedup tuples for the same edge.
 */
export type NewInteraction = { type: InteractionType, target_id: bigint | null, post_id: bigint | null, comment_id: bigint | null, };
