// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewPost = { category: string | null, body: string, 
/**
 * Optional id of an already-uploaded media asset to attach. The frontend sets
 * this after the presigned-upload + finalize flow.
 */
media_id: bigint | null, };
