// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewPost = { category: string | null, body: string, 
/**
 * Optional id of an already-uploaded media asset to attach. The frontend sets
 * this after the presigned-upload + finalize flow.
 */
media_id: bigint | null, 
/**
 * `public` (default) or `private` (P-4/A4g). A private post is the creator's
 * paywalled-area content: hidden from every read path unless the viewer is
 * entitled, never analysed by ingestion. The value is whitelisted in the
 * service; the DB CHECK (migration 0021) is the fail-closed backstop.
 */
area: string, };
