// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaKind } from "./MediaKind";

/**
 * Request to begin an upload.
 */
export type NewUpload = { kind: MediaKind, 
/**
 * MIME type, e.g. "video/mp4". Its top-level type must match `kind`.
 */
content_type: string, 
/**
 * PT price to unlock this asset. 0 (default) means free / open.
 */
unlock_price: bigint, };
