// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Post = { id: bigint, author_id: bigint, category: string | null, body: string | null, created_at: string, 
/**
 * Cold-start feed signal (popularity + recency); 0 at creation (Dossier §4.2).
 */
popularity_score: number, 
/**
 * Optional attached media asset (image/video/audio). Access is gated by the
 * asset's own unlock_price — see `GET /media/:id`.
 */
media_id: bigint | null, 
/**
 * `public` or `private` (P-4, migration 0021). A private post is the
 * creator's paywalled area; it must never surface in a read path unless the
 * viewer is entitled — enforced in the repository queries (see the
 * post-visibility invariant doc). A post projected here is one the viewer
 * may already see, so this field is a display hint (e.g. a lock badge), not
 * itself the gate.
 */
area: string, 
/**
 * DISTINCT users with an active (non-retracted) like on this post, computed
 * live from the interaction journal (ADR 0012) — no denormalised counter to
 * drift. Distinct ACTORS, not journal rows: the economic journal may hold
 * one weighted row per epoch for the same (actor, post) (daily re-engagement
 * edges), but the display counter is per-user boolean semantics — otherwise
 * one account could pump a public counter by +1/day via the raw API.
 */
like_count: bigint, 
/**
 * Whether the REQUESTING viewer holds an active like on this post — what the
 * like button hydrates from. `false` for anonymous reads.
 */
liked_by_me: boolean, };
