// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Post = { id: bigint, author_id: bigint, category: string | null, body: string | null, created_at: string, 
/**
 * Cold-start feed signal (popularity + recency); 0 at creation (Dossier §4.2).
 */
popularity_score: number, };
