// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to configure the caller's OWN private area (A3). The creator id
 * comes from the authenticated session, never from the body or path.
 */
export type PrivateAreaConfigRequest = { 
/**
 * One of `free`, `one_time`, `subscription`, `per_post` (the CREATOR's
 * choice — owner decision 2026-07-08).
 */
access_model: string, 
/**
 * Integer EUR cents for AREA access: required (> 0) for
 * one_time/subscription, must be 0 for free/per_post (per-post prices
 * attach to posts when their stage lands).
 */
price_cents: bigint, description: string, };
