// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A creator's private-area terms. This is the public OFFER a potential
 * buyer decides against — nothing in it is secret.
 */
export type PrivateAreaView = { creator_id: bigint, access_model: string, price_cents: bigint, currency: string, description: string, };
