// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operator-only request to set a creator's referral contract (P-2): the cut in
 * basis points and how long referrals recruited FROM NOW ON earn. Terms are
 * frozen onto each referral at registration, so changing a contract never
 * silently rewrites existing referrals.
 */
export type ReferralTermsRequest = { bps: number, duration_epochs: bigint, note?: string, };
