// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The stored referral contract, echoed back on write.
 */
export type ReferralTerms = { referrer_id: bigint, bps: number, duration_epochs: bigint, note: string | null, };
