// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegisterRequest = { email: string, password: string, declared_categories: Array<string>, 
/**
 * Referral code of the user who invited this one (MASTERPLAN P-2). An
 * UNKNOWN code fails the registration (400 invalid_referral_code) rather
 * than being dropped silently — a typo must surface, not cost the
 * referrer their cut.
 */
referral_code?: string, };
