// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user's report of a post (moderation). The reporter is the session user.
 */
export type ReportRequest = { reason: string, };
