// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operator review row: a reported post with how many reports it has.
 */
export type ReportedPost = { post_id: bigint, report_count: bigint, hidden: boolean, };
