// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodePurpose } from "./CodePurpose";

/**
 * Request a one-time code by email (recovery entry point). The response is
 * always 204 regardless of whether the account exists — no enumeration.
 */
export type RequestCodeRequest = { email: string, purpose: CodePurpose, };
