// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Set a new password using an emailed reset code. On success every existing
 * session for the account is invalidated and a fresh one is returned.
 */
export type ResetPasswordRequest = { email: string, code: string, new_password: string, };
