// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user's authorization role. Maps 1:1 to the Postgres `user_role` enum.
 * `User` is the default (non-privileged); `Operator` may run admin actions
 * such as epoch settlement.
 */
export type Role = "user" | "operator";
