// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of settling (or attempting to settle) one epoch.
 */
export type SettlementSummary = { epoch_k: bigint, 
/**
 * PT base units minted this epoch (0 if there were no eligible participants).
 */
emission: bigint, 
/**
 * Number of users that participated in the interaction graph this epoch.
 */
user_count: number, 
/**
 * True if the epoch had already been settled and this call was a no-op.
 */
already_settled: boolean, };
