// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type User = { id: bigint, created_at: string, declared_categories: Array<string>, 
/**
 * Bot gate v_i: manual early, heuristic later, KYC in Phase 2 (Dossier §4.4).
 */
bot_gate_v: boolean, 
/**
 * Public profile stat: DISTINCT (liker, post) pairs with an active
 * (non-retracted) like on this user's PUBLIC, non-hidden posts (ADR 0012) —
 * a fan liking three posts counts three, but never twice for the same post
 * (distinct pairs, not journal rows; see `Post::like_count`). Deliberately
 * viewer-independent and blind to private-area engagement, so the public
 * number never leaks paywalled activity. Comment-likes and direct
 * user-likes are not counted — the stat mirrors what the profile grid
 * shows: the posts.
 */
likes_received: bigint, 
/**
 * Public profile stat: how many users follow THIS user, live from the
 * `follows` table (the API previously only exposed the *following* list).
 * Viewer-independent, like `likes_received`.
 */
followers_count: bigint, };
