-- Referral system (MASTERPLAN P-2), foundations. Terms are SNAPSHOTTED onto
-- each referral at registration time — auditable, and a later contract change
-- never silently rewrites existing referrals. The cut itself is applied at
-- settlement and is CONSERVING: it comes out of the referred user's payout;
-- nothing extra is ever minted.

-- Every user gets a shareable referral code, generated by the DATABASE default
-- (volatile default ⇒ Postgres evaluates it per row, existing rows included) —
-- so registration needs no code change to hand out codes. 12 hex chars = 48
-- bits; the UNIQUE index turns the practically-impossible collision into a
-- failed insert rather than corrupted data.
ALTER TABLE users
    ADD COLUMN referral_code TEXT NOT NULL DEFAULT substr(md5(random()::text), 1, 12);
CREATE UNIQUE INDEX users_referral_code ON users (referral_code);

-- Who referred whom, with the frozen terms. One referrer per referred user,
-- one level only (a referred user's own referrals are separate rows).
CREATE TABLE referrals (
    referred_id       BIGINT PRIMARY KEY REFERENCES users (id),
    referrer_id       BIGINT NOT NULL REFERENCES users (id),
    bps               INT NOT NULL CHECK (bps >= 0 AND bps <= 10000),
    valid_until_epoch BIGINT NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (referred_id <> referrer_id)
);
CREATE INDEX referrals_referrer ON referrals (referrer_id);

-- Operator-set per-creator contract overrides (e.g. 5% for a negotiated
-- period), consulted at registration when the terms are frozen.
CREATE TABLE referral_terms (
    referrer_id     BIGINT PRIMARY KEY REFERENCES users (id),
    bps             INT NOT NULL CHECK (bps >= 0 AND bps <= 10000),
    duration_epochs BIGINT NOT NULL CHECK (duration_epochs >= 0),
    note            TEXT,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The settlement cut is journaled as its own ledger kind.
ALTER TABLE ledger_entries DROP CONSTRAINT ledger_entries_kind_check;
ALTER TABLE ledger_entries
    ADD CONSTRAINT ledger_entries_kind_check
        CHECK (kind IN ('mint', 'unlock_debit', 'unlock_credit', 'unlock_burn', 'referral'));
