// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned on register/login. The token is shown ONCE; only its hash is stored.
 */
export type AuthResponse = { token: string, user_id: bigint, };
