// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Public view of an asset. `object_key` is internal and omitted; `playback_url`
 * is a presigned GET URL, present only once the asset is ready.
 */
export type MediaAssetView = { id: bigint, owner_id: bigint, kind: string, content_type: string, status: string, size_bytes: bigint | null, playback_url: string | null, 
/**
 * True once an HLS rendition has been produced.
 */
hls_ready: boolean, 
/**
 * PT price to unlock; 0 means free.
 */
unlock_price: bigint, };
