// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InteractionType } from "./InteractionType";

/**
 * Request to record an interaction. `target_id` (the other user) and `post_id`
 * are optional — a like targets a post, a follow targets a user, etc.
 */
export type NewInteraction = { type: InteractionType, target_id: bigint | null, post_id: bigint | null, };
