// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a paid unlock — the split is reported for transparency.
 */
export type UnlockSummary = { asset_id: bigint, viewer_id: bigint, price: bigint, creator_received: bigint, company_fee: bigint, burned: bigint, 
/**
 * True if the viewer had already unlocked it (no charge applied).
 */
already_unlocked: boolean, };
