// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the client needs to upload directly to the object store.
 */
export type UploadTicket = { asset_id: bigint, object_key: string, 
/**
 * Presigned PUT URL — upload the bytes here with the declared content-type.
 */
upload_url: string, expires_in_secs: bigint, };
