// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type User = { id: bigint, created_at: string, declared_categories: Array<string>, 
/**
 * Bot gate v_i: manual early, heuristic later, KYC in Phase 2 (Dossier §4.4).
 */
bot_gate_v: boolean, };
