// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operator-only request to set a user's bot-gate (verified) flag. The gate is
 * the hard veto that decides who earns gems, so it is mutable ONLY through the
 * operator endpoint — never self-asserted at registration.
 */
export type VerificationRequest = { verified: boolean, };
